import {pricingPage} from '../Page Objects/pricing'

// Test data


describe('Lodgify Pricing / Contact page', () => {
    it('Test 1 - Checking pricing plans ', () => {
    cy.visit('http://localhost:8080/Pricing.html');
    cy.title().should('include', 'Pricing');
    cy.get('#scroll-prop-plan').clear({force:true})
    cy.get('#scroll-prop-plan').type(50)
    cy.get('body > div.content-wrapper > div.section.pad-top-0.pad-bot-2 > div.container.container-md > div.property-scroll-box > div.scroll-box > div:nth-child(2) > div.slider-handle.min-slider-handle.round')
        .should('be.visible').and('exist')
    cy.get('.price-card-starter > .price-item')
        .should('be.visible').and('exist')
    cy.get('.price-card-starter > .price-item > :nth-child(1) > .plan-price > .total-sum')
        .should('be.visible').and('contain', '64' )
    cy.get('.price-card-starter > .price-item > :nth-child(2) > .wd-100 > .btn')
        .should('be.visible').and('contain', 'Get Started')
    cy.get(':nth-child(2) > .price-item')
        .should('be.visible').and('exist')
    cy.get(':nth-child(2) > .price-item > :nth-child(1) > .plan-price > .total-sum')
        .should('be.visible').and('contain', '375' )
    cy.get(':nth-child(2) > .price-item > :nth-child(2) > .wd-100 > .btn')
        .should('be.visible').and('contain', 'Get')
    cy.get(':nth-child(3) > .price-item')
        .should('be.visible').and('exist')
    cy.get(':nth-child(3) > .price-item > :nth-child(1) > .plan-price > .total-sum')
        .should('be.visible').and('contain', '518' )
    cy.get(':nth-child(3) > .price-item > :nth-child(2) > .wd-100 > .btn')
        .should('be.visible').and('contain', 'Started')
      
  })

  it('Test 2 - Checking currencies', () => {
    cy.title().should('include', 'Pricing');
    cy.get('.row-sm > :nth-child(1)')
      .should('be.visible').and('contain', 'Do you want to see other currencies?')
    cy.get('.price-currency-select')
      .select('eur')
    cy.get('.price-card-starter > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '60€' )
    cy.get(':nth-child(2) > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '330€' )
    cy.get(':nth-child(3) > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '466€' )
    cy.get('.row-sm > :nth-child(1)')
        .should('be.visible').and('contain', 'Do you want to see other currencies?')
    cy.get('.price-currency-select')
        .select('gbp')
    cy.get('.price-card-starter > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '£51' )
    cy.get(':nth-child(2) > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '£294' )
    cy.get(':nth-child(3) > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '£414' )
    cy.get('.row-sm > :nth-child(1)')
        .should('be.visible').and('contain', 'Do you want to see other currencies?')
    cy.get('.price-currency-select')
        .select('usd')
        cy.get('.price-card-starter > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '$64' )
    cy.get(':nth-child(2) > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '$375' )
    cy.get(':nth-child(3) > .price-item > :nth-child(1) > .plan-price')
        .should('be.visible').and('contain', '$518' )

    
    })

    it('Test 3 - Other page tests', () => {
        cy.get('.head-top-bar > .container')
            .should('be.visible').and('exist')
        cy.get('#menu-item-15007 > .dropdown-toggle')
            .should('be.visible').and('exist')
        cy.get('#menu-item-13168 > .dropdown-toggle')
            .should('be.visible').and('exist')
        cy.get('#menu-item-8806 > .dropdown-toggle')
            .should('be.visible').and('exist')
        cy.get('#menu-item-31 > a')
            .should('be.visible').and('exist')
        cy.get('#menu-item-32 > a')
            .should('be.visible').and('exist')
        cy.get('.wd-100 > .push-bot-3')
            .should('be.visible').and('exist')
        cy.get('.property-scroll-box')
            .should('be.visible').and('exist')
        cy.get('[data-price-period="1"] > span')
            .should('be.visible').and('exist')
        cy.get('[data-price-period="1"] > span')
            .click({force:true})
        cy.get('[data-price-period="2"]')
            .should('be.visible').and('exist')
        cy.get('[data-price-period="2"]')
            .click({force:true})
        cy.get('[data-price-period="3"] > a')
            .should('be.visible').and('exist')
        cy.get('[data-price-period="3"] > a')
            .click({force:true})
        cy.get(':nth-child(1) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(2) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(3) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(4) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(5) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(6) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(7) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(8) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(9) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(10) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(11) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(12) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(13) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(14) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(15) > .faq-question')
            .click({force:true})
        cy.get(':nth-child(16) > .faq-question')
            .click({force:true})
        cy.get('.sct-heading-box')
            .should('be.visible').and('exist')
        cy.get(':nth-child(4) > .container > .row > :nth-child(1)')
            .should('be.visible').and('exist')
        cy.get(':nth-child(4) > .container > .row > :nth-child(2)')
            .should('be.visible').and('exist')
        cy.get(':nth-child(4) > .container > .row > :nth-child(3)')
            .should('be.visible').and('exist')
        cy.get('#nav_menu-2')
            .should('be.visible').and('exist')
        cy.get('#nav_menu-3')
            .should('be.visible').and('exist')
        cy.get('#nav_menu-4')
            .should('be.visible').and('exist')
        cy.get('#nav_menu-5')
            .should('be.visible').and('exist')
        cy.get('#cn-accept-cookie')
            .should('be.visible').and('exist')
        cy.get('#cn-accept-cookie')
            .click({force:true})

    
        
        })
})